# Generated by Django 3.0 on 2020-01-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor', '0003_auto_20200118_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='total_occupants',
            field=models.IntegerField(),
        ),
    ]
