# Generated by Django 3.0 on 2020-01-18 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor', '0004_auto_20200118_1810'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Neighborhood',
        ),
    ]
