# Generated by Django 3.0 on 2020-01-18 20:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neighbor', '0008_bussiness'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bussiness',
            new_name='Business',
        ),
    ]
