# Generated by Django 3.0 on 2020-01-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor', '0009_auto_20200118_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='bussiness_email',
            field=models.CharField(max_length=100),
        ),
    ]
