# Generated by Django 3.0 on 2020-01-19 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor', '0010_auto_20200118_2019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
