# Generated by Django 3.0 on 2020-01-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor', '0013_auto_20200119_0905'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
    ]
