# Generated by Django 3.0 on 2020-01-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor', '0015_business'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
    ]
